# ABOUT PAGE CONTENT
about_name: "om-oss"
title: "Om Lopskalender.com"
description: "Lopskalender.com er et samlingsted for alle norske løp. Her finner du alle løp og løpshendelser i Norge 2024. Vi lister opp alle løp og løpshendelser i Norge 2024. Finn ditt neste mil-løp, tids-løp, terrengløp, halvmaraton, maraton eller ultramaraton hos oss i dag."

# ABOUT PAGE
main_header: "Norges mest komplette liste over langdistanseløp"
paragraph1: |
  Velkommen til den ultimate ressursen for løpeentusiaster i Norge!
  Vår nettside er den mest omfattende listen over løpshendelser i landet, og
  vårt mål er å gjøre det enklere enn noensinne å finne din neste
  utfordring.
paragraph2: |
  Med vårt brukervennlige grensesnitt kan du filtrere løpene basert på
  distanse, type løp og sted. Enten du er en nybegynner som
  leter etter ditt nærmeste mil-løp eller en ultraløper som leter etter
  100 miles-løp, så har vi noe for deg. Vårt oppdrag er å
  tilby konsis, men oppdatert informasjon om alle
  løpearrangementer i Norge. Vi er selv aktive som både løpere og
  arrangører, og vi gjør kontinuerlig kontroll og utvidelse for å
  sikre at vår database alltid er så nøyaktig og komplett som
  mulig. Du kan stole på at vi gir pålitelig
  informasjon om løpsdatoer, steder og registreringsdetaljer. Hvis
  det er vanskelig å huske Lopskalender.com, finner du oss lett når du
  søker etter nøkkelord som "maraton Norge 2023" eller "ultramaraton
  Norge"
paragraph3: |
  I tillegg til vår omfattende liste over løp, er det langsiktige målet
  å også tilby ressurser og tips for løpere på alle nivåer.
  Fra treningsplaner til kostholdsveiledning, ønsker vi å være din
  one-stop-shop for alt relatert til løping. Bli med i vårt fellesskap av
  lidenskapelige løpere og ta løpeferden din til neste nivå.
paragraph4: |
  Hvis du har spørsmål til oss eller tilbakemeldinger om innholdet, er du velkommen til å
  kontakte oss på:
mail_to_link: "loppkartan@gmail.com"
add_new_race_box_header: "Nok om oss, finn ditt neste løp ved hjelp av kartet eller listen nedenfor:"
map_button_text: "KARTET"
list_button_text: "LISTEN"
