# ABOUT PAGE CONTENT
about_name: "om-oss"
title: "Om Loppkartan.se"
description: "Loppkartan.se är en samlingsplats för alla svenska löplopp. Här hittar du alla lopp och löpartävlingar i Sverige 2024. Vi listar alla lopp och löpartävlingar i Sverige 2024. Hitta ditt nästa millopp, tidslopp, traillopp, halvmara, marathon eller ultra marathon hos oss idag."

# ABOUT PAGE
main_header: "Sveriges mest kompletta lista över långlopp"
paragraph1: |
  Välkommen till den ultimata resursen för löparentusiaster i Sverige!
  Vår webbplats är den mest omfattande listan över löplopp i landet, och
  vår ambition är att göra dett enklare än någonsin att hitta din nästa
  utmaning.
paragraph2: |
  Med vårt användarvänliga gränssnitt kan du filtrera loppen baserat på
  distans, typ av lopp och plats. Oavsett om du är en nybörjare som
  letar efter ditt närmsta millopp eller en ultra-löpare som letar efter
  100 miles-lopp, så har vi dig för dig. Vårt uppdrag är att
  tillhandahålla koncis men uppdaterad information om alla
  löparevenemang i Sverige. Vi är själva aktiva som både löpare och
  tävlingsarrangörer och gör löpande kontroll och utökning för att
  säkerställa att vår databas alltid är så korrekt och komplett som
  möjligt. Du kan lita på att vi tillhandahåller tillförlitlig
  information om tävlingsdatum, platser och registreringsdetaljer. Är
  det svårt att komma ihåg loppkartan.se så hittar du oss lätt när du
  söker efter nyckelord som "maraton sverige 2023" eller "ultramaraton
  sverige"
paragraph3: |
  Förutom vår omfattande lista över lopp, är den långsiktiga ambitionen
  att också tillhandahålla resurser och tips för löpare på alla nivåer.
  Från träningsplaner till kostrådgivning, vill vi vara din
  one-stop-shop för allt löprelaterat. Gå med i vår gemenskap av
  passionerade löpare och ta din löparresa till nästa nivå.
paragraph4: |
  Har du frågor till oss eller synpunkter på innehållet får du gärna
  kontakta oss på:
mail_to_link: "loppkartan@gmail.com"
add_new_race_box_header: "Nog om oss, leta rätt på ditt nästa lopp med hjälp av kartan eller listan nedan:"
map_button_text: "KARTAN"
list_button_text: "LISTAN"
