# ADD RACE PAGE
add_race_name: "legg-til-lop"
map_message: "Plasser løpet ditt ved å klikke på kartet"
date_text: "Dato"
type_text: "Type underlag / Type løp"
type_select_placeholder: "Velg underlag / type løp"
type_options:
  - "Landsvei"
  - "Terreng"
  - "Fjell"
  - "Backyard Ultra"
  - "Stafett"
  - "Bane"
  - "Annet"
name_label: "Løpets navn:"
name_placeholder: "f.eks. Kungsholmen rundt"
distance_label: "Distanser:"
distance_placeholder: "10 km, halvmaraton og barneløp"
place_label: "Sted:"
place_placeholder: "Rålambshovsparken, Stockholm"
organizer_label: "Arrangør:"
organizer_contact_placeholder: "FK Studenterna"
organizer_contact_label: "E-post til kontaktperson:"
organizer_mail_placeholder: "loppkartan@gmail.com"
website_label: "Arrangørens nettside:"
website_placeholder: "https://fkstudenterna.se/"
summary_label: "Beskriv løpet"
summary_placeholder: "KfS Kungsholmen Rundt er en milbane med lange, flate strekninger ..."
preview_button: "Forhåndsvis"
submit_button: "Send"
preview_exit_button: "Tilbake"
