# ADD RACE PAGE
add_race_name: "lagg-till-lopp"
map_message: "Placera ut ditt lopp genom att klicka på kartan"
date_text: "Datum"
type_text: "Typ av underlag / Typ av lopp"
type_select_placeholder: "Välj underlag / typ av lopp"
type_options:
  - "Landsväg"
  - "Terräng"
  - "Trail"
  - "Backyard Ultra"
  - "Stafett"
  - "Bana"
  - "Övrigt"
name_label: "Loppets namn:"
name_placeholder: "t ex Kungsholmen runt"
distance_label: "Distanser:"
distance_placeholder: "10 km, halvmara och knattelopp"
place_label: "Plats:"
place_placeholder: "Rålambshovsparken, Stockholm"
organizer_label: "Arrangör:"
organizer_contact_placeholder: "FK Studenterna"
organizer_contact_label: "Mail till kontaktperson:"
organizer_mail_placeholder: "info@LoppKartan.se"
website_label: "Arrangörshemsida:"
website_placeholder: "https://fkstudenterna.se/"
summary_label: "Beskriv loppet"
summary_placeholder: "KfS Kungsholmen Runt är en milbana med långa, flacka rakor ..."
preview_button: "Förhandsgranska"
submit_button: "Skicka"
preview_exit_button: "Tillbaka"
