# CONTACT PAGE CONTENT
contact_name: "kontakt"
title: "Kontakt oss på Lopskalender.com"
description: "Kontakt oss på Lopskalender.com hvis du har spørsmål eller synspunkter på innholdet i et løp."
main_header: "Kontaktinformasjon"
secondary_header1: "Vi som står bak løpekartet"
paragraph1: |
  Denne nettsiden er opprettet av frustrasjon over mangelen på en
  komplett kilde for å finne nye løp. Vi som står bak siden er selv
  aktive løpere og deltar jevnlig i løp. Siden er et hobbyprosjekt og
  finansieres utelukkende av lidenskap og funksjonærboller. Vi tar gjerne
  imot tilbakemeldinger om hvordan vi kan forbedre brukeropplevelsen,
  eller hvis du har synspunkter på innholdet i et løp, kan du gjerne
  kontakte oss på:
mail_to_link: "loppkartan@gmail.com"
secondary_header2: "Legg til manglende løp"
paragraph2: |
  Hvis du allerede har gått gjennom listen grundig og føler at det mangler
  et løp. Følg gjerne lenken nedenfor til vårt arrangørsformular og
  fyll ut opplysningene, så legger vi til løpet så snart som mulig. Dette
  kan også gjøres av ikke-arrangører og ordensfolk som mener at vi
  mangler noe. Lenken er her:
add_race_link: "/legg-til-lop.html"
add_race_link_text: "Legg til løp"

add_new_race_box_header: "Nok om oss, finn ditt neste løp ved hjelp av kartet eller listen nedenfor:"
map_button_text: "KARTET"
list_button_text: "LISTEN"
