# CONTACT PAGE CONTENT
contact_name: "kontakt"
title: "Kontakta oss på loppkartan.se"
description: "Kontakta oss på loppkartan.se om du har frågor eller synpunkter på innehållet i något lopp."
main_header: "Kontaktinformation"
secondary_header1: "Vi som står bakom loppkartan"
paragraph1: |
  Den här webbplatsen är skapad ur frustration över att det inte finns
  någon komplett källa till att hitta nya löpartävlingar. Vi som står
  bakom sajten är själva aktiva löpare och springer
  regelbundet lopp. Sidan är ett hobbyprojekt och finansieras enbart av
  passion och funktionärsbullar. Vi tar tacksamt emot feedback på hur vi
  kan göra användarupplevelsen bättre, eller om ni har synpunkter på
  innehållet i något lopp så får ni gärna kontakta oss på:
mail_to_link: "loppkartan@gmail.com"
secondary_header2: "Lägg till saknade lopp"
paragraph2: |
  Om ni redan har gått igenom listan grundligt och känner att ni saknade
  något lopp. Följ då gärna nedan länk till vårat arrangörsformulär och
  fyll i uppgifterna så lägger vi upp loppet snarast. Detta går även bra
  att göra för ickearrangörer samt vänner av ordning som tycker att vi
  saknar något. Länken är här:
add_race_link: "/lagg-till-lopp.html"
add_race_link_text: "Lägg till lopp"

add_new_race_box_header: "Nog om oss, leta rätt på ditt nästa lopp med hjälp av kartan eller listan nedan:"
map_button_text: "KARTAN"
list_button_text: "LISTAN"
