#Main site

domain: "loppkartan.se"
google_analytics_id: "G-EJBRM67XCS"

title: "Sveriges mest kompletta lista och kalender över löpartävlingar och lopp 2024"
title_alternative: "Loppkartan som får Sverige att springa fler lopp 2024" # This is used for map
title_find: "Sveriges mest kompletta lista och kalender över löpartävlingar och lopp"
seo_county_title: "Alla lopp och löpartävlingar i %s"
seo_category_title: "Alla %s och andra löpartävlingar i Sverige. På ett och samma ställe."
seo_checkboxes_title: "Alla svenska lopp och löpartävlingar på %s. På ett och samma ställe."

description: "Vi har samlat alla svenska löplopp i en datumsorterad lista. Hitta ditt nästa millopp, tidslopp, traillopp, halvmara, marathon eller ultra marathon hos oss idag."
description_alternative: "Vi har samlat alla svenska löplopp i en interaktiv karta. Hitta ditt nästa millopp, tidslopp, traillopp, halvmara, marathon eller ultra marathon hos oss idag."
seo_county_description: "Här har vi samlat alla lopp och löpartävlingar i %s 2024. Hitta ditt nästa millopp, tidslopp, traillopp, halvmara, marathon eller ultra marathon hos oss idag."
seo_category_description: "Här har vi samlat alla %s och andra löpartävlingar i Sverige 2024. Hitta ditt nästa lopp hos oss idag."
seo_checkboxes_description: "Här har vi samlat alla svenska lopp och löpartävlingar på %s i Sverige 2024. Hitta ditt nästa lopp hos oss idag."

promotion_text: "Obetalt samarbete med:"
promotion_link:
  url: "http://www.kungsholmenrunt.se/Main/Start.asp"
  target: "_blank"
promo_logo:
  src: "/img/logokr_bluebg.jpg"
  class: "promo-logo-box"
list_button_text: "Lista"
map_button_text: "Karta"
menu_button_text: "Meny"
menu_items:
  - id: "navIndex"
    text: "Loppkartan"
    url: "/index.html"
  - id: "navLopplistan"
    text: "Lopplistan"
    url: "/lopplistan.html"
  - id: "navAbout"
    text: "Om Loppkartan.se"
    url: "/om-oss.html"
  - id: "navContact"
    text: "Kontaktuppgifter"
    url: "/kontakt.html"
  - id: "navAddRace"
    text: "Lägg till lopp"
    url: "/lagg-till-lopp.html"

main_header: "Sveriges mest kompletta loppkalender för löpare"
main_header_alternative: "Sveriges mest kompletta loppkalender för löpare"
main_subheader: "Här listar vi alla Sveriges lopp och löpartävlingar under 2024.
  Filtrera fram ditt nästa 10 km millopp, halvmaraton eller backyard
  ultra."
main_subheader_alternative: "Hitta ditt nästa lopp! Välj distans, som millopp eller marathon, samt underlag som trail eller landsväg."

days_filter_text: "Lopp mellan: "
distance_filter_text: "Distans mellan: "

more_info_text: "Mer info"
ending_header: "Saknar du ditt lopp på kartan? Lägg till
  det här!"

add_race_button:
  id: "addRaceButton"
  url: "/lagg-till-lopp.html"
  class: "add-race-button border-style"
  label: "Lägg till lopp"
checkbox_mapping:
  - container_id: "relayCheckboxContainer"
    checkbox_id: "relayCheckbox"
    check_icon_class: "check-icon-relay"
    label_text: "Stafett"
  - container_id: "backyardCheckboxContainer"
    checkbox_id: "backyardCheckbox"
    check_icon_class: "check-icon-backyard"
    label_text: "Backyard"
  - container_id: "terrainCheckboxContainer"
    checkbox_id: "terrainCheckbox"
    check_icon_class: "check-icon-terrain"
    label_text: "Terräng"
  - container_id: "trailCheckboxContainer"
    checkbox_id: "trailCheckbox"
    check_icon_class: "check-icon-trail"
    label_text: "Trail"
  - container_id: "roadCheckboxContainer"
    checkbox_id: "roadCheckbox"
    check_icon_class: "check-icon-road"
    label_text: "Landsväg"
  - container_id: "trackCheckboxContainer"
    checkbox_id: "trackCheckbox"
    check_icon_class: "check-icon-track"
    label_text: "Löparbana"

month_mapping:
  "01": "Januari"
  "02": "Februari"
  "03": "Mars"
  "04": "April"
  "05": "Maj"
  "06": "Juni"
  "07": "Juli"
  "08": "Augusti"
  "09": "September"
  "10": "Oktober"
  "11": "November"
  "12": "December"

month_mapping_short:
  "01": "jan."
  "02": "feb."
  "03": "mars"
  "04": "apr."
  "05": "maj"
  "06": "juni"
  "07": "juli"
  "08": "aug."
  "09": "sep."
  "10": "okt."
  "11": "nov."
  "12": "dec."

distance_mapping:
  backyard: Backyard Ultra
  time: Tidslopp
  relay: Stafett

distance_units:
  - range: [20.9, 21.3]
    label: Halvmarathon
  - range: [41.9, 42.4]
    label: Marathon

county_label_text: "Alla län"
county_mapping:
  "Stockholms": "Stockholm"
  "Uppsala": "Uppsala"
  "Södermanlands": "Södermanland"
  "Östergötlands": "Östergötland"
  "Jönköpings": "Jönköping"
  "Kronobergs": "Kronoberg"
  "Kalmar": "Kalmar"
  #"Kalmar":  "Öland"
  "Gotlands": "Gotland"
  "Blekinge": "Blekinge"
  "Skåne": "Skåne"
  "Hallands": "Halland"
  "Västra Götalands": "Västra Götaland"
  #"Västra Götalands":  "Göteborg"
  "Värmlands": "Värmland"
  "Örebro": "Örebro"
  "Västmanlands": "Västmanland"
  "Dalarnas": "Dalarna"
  "Gävleborgs": "Gävleborg"
  "Västernorrlands": "Västernorrland"
  "Jämtlands": "Jämtland"
  "Västerbottens": "Västerbotten"
  "Norrbottens": "Norrbotten"

category_label_text: "Loppkategori"
category_mapping:
  "1500 meter":
    range: [1.5, 1.5]
  "3000 meter":
    range: [3, 3]
  "5000 meter":
    range: [5, 5]
  "10000 meter":
    range: [10, 10]
  "5 km":
    range: [4, 6]
  "10 km":
    range: [9, 11]
  "Millopp":
    range: [9, 11]
  "Halvmarathon":
    range: [20, 22]
  "Marathon":
    range: [40, 44]
  "Backyard Ultra": "backyard"
  "Ultra Marathon":
    range: [42, 500]
  "50 miles":
    range: [75, 100]
  "100 miles":
    range: [150, 170]
  "200 miles":
    range: [300, 500]
  "50 km":
    range: [45, 55]
  "100 km":
    range: [90, 110]
