#Main site

domain: "lopskalender.com"
google_analytics_id: "G-F83PGVEH79"

title: "Norges mest komplette terminliste og kalender over løp og mosjonsløp 2024"
title_alternative: "Løpekartet som får Norge til å løpe flere løp 2024" # This is used for map
title_find: "Norges mest komplette terminliste og kalender over løp og mosjonsløp"
seo_county_title: "Alle løp og mosjonsløp i %s"
seo_category_title: "Alle %s og andre løp i Norge. På ett og samme sted."
seo_checkboxes_title: "Alle norske løp og mosjonsløp på %s. På ett og samme sted."

description: "Vi har samlet alle norske løp og mosjonsløp i en datert terminliste. Finn ditt neste mosjonsløp, terrengløp, fjelløp, halvmaraton, maraton eller ultraløp hos oss i dag."
description_alternative: "Vi har samlet alle norske løp og mosjonsløp på et interaktivt kart. Finn ditt neste mosjonsløp, terrengløp, fjelløp, halvmaraton, maraton eller ultraløp hos oss i dag."
seo_county_description: "Her har vi samlet alle løp og mosjonsløp i %s 2024. Finn ditt neste mosjonsløp, terrengløp, fjelløp, halvmaraton, maraton eller ultraløp hos oss i dag."
seo_category_description: "Her har vi samlet alle %s og andre løp i Norge 2024. Finn ditt neste løp hos oss i dag."
seo_checkboxes_description: "Her har vi samlet alle norske løp og mosjonsløp på %s i Norge 2024. Finn ditt neste løp hos oss i dag."

promotion_text: "Ubetalt samarbeid med:"
promotion_link:
  url: "http://www.kungsholmenrunt.se/Main/Start.asp"
  target: "_blank"
promo_logo:
  src: "/img/logokr_bluebg.jpg"
  class: "promo-logo-box"
list_button_text: "Liste"
map_button_text: "Kart"
menu_button_text: "Meny"
menu_items:
  - id: "navIndex"
    text: "Løpekartet"
    url: "/index.html"
  - id: "navLopsliste"
    text: "Løpplisten"
    url: "/lopsliste.html"
  - id: "navAbout"
    text: "Om Løpekartan.no"
    url: "/om-oss.html"
  - id: "navContact"
    text: "Kontaktinformasjon"
    url: "/kontakt.html"
  - id: "navAddRace"
    text: "Legg til løp"
    url: "/legg-til-lop.html"

main_header: "Norges mest komplette løpekalender for løpere"
main_header_alternative: "Norges mest komplette løpekalender for løpere"
main_subheader: "Her lister vi opp alle Norges løp og mosjonsløp i 2024.
  Filtrer frem ditt neste 10 km mosjonsløp, halvmaraton eller backyard
  ultra."
main_subheader_alternative: "Finn ditt neste løp! Velg distanse, som mosjonsløp eller maraton, samt underlag som terreng eller vei."

days_filter_text: "Løp mellom: "
distance_filter_text: "Distanse mellom: "

more_info_text: "Mer info"
ending_header: "Mangler du ditt løp på kartet? Legg til
  det her!"

add_race_button:
  id: "addRaceButton"
  url: "/legg-til-lop.html"
  class: "add-race-button border-style"
  label: "Legg til løp"
checkbox_mapping:
  - container_id: "relayCheckboxContainer"
    checkbox_id: "relayCheckbox"
    check_icon_class: "check-icon-relay"
    label_text: "Stafett"
  - container_id: "backyardCheckboxContainer"
    checkbox_id: "backyardCheckbox"
    check_icon_class: "check-icon-backyard"
    label_text: "Backyard Ultra"
  - container_id: "terrainCheckboxContainer"
    checkbox_id: "terrainCheckbox"
    check_icon_class: "check-icon-terrain"
    label_text: "Terreng"
  - container_id: "trailCheckboxContainer"
    checkbox_id: "trailCheckbox"
    check_icon_class: "check-icon-trail"
    label_text: "Fjelløp"
  - container_id: "roadCheckboxContainer"
    checkbox_id: "roadCheckbox"
    check_icon_class: "check-icon-road"
    label_text: "Vei"
  - container_id: "trackCheckboxContainer"
    checkbox_id: "trackCheckbox"
    check_icon_class: "check-icon-track"
    label_text: "Løpebane"

month_mapping:
  "01": "Januar"
  "02": "Februar"
  "03": "Mars"
  "04": "April"
  "05": "Mai"
  "06": "Juni"
  "07": "Juli"
  "08": "August"
  "09": "September"
  "10": "Oktober"
  "11": "November"
  "12": "Desember"

month_mapping_short:
  "01": "jan."
  "02": "feb."
  "03": "mars"
  "04": "apr."
  "05": "mai"
  "06": "juni"
  "07": "juli"
  "08": "aug."
  "09": "sep."
  "10": "okt."
  "11": "nov."
  "12": "des."

distance_mapping:
  backyard: Backyard Ultra
  time: Tidsløp
  relay: Stafett

distance_units:
  - range: [20.9, 21.3]
    label: Halvmaraton
  - range: [41.9, 42.4]
    label: Maraton

county_label_text: "Alle fylker"
county_mapping:
  "Rogaland":"Rogaland"
  "Vestfold og Telemark":"Vestfold og Telemark"
  "Nordland":"Nordland"
  "Agder":"Agder"
  "Innlandet":"Innlandet"
  "Møre og Romsdal":"Møre og Romsdal"
  "Vestland":"Vestland"
  "Oslo":"Oslo"
  "Viken":"Viken"
  "Trøndelag":"Trøndelag"
  "Troms og Finnmark":"Troms og Finnmark"

category_label_text: "Løpkategori"
category_mapping:
  "1500 meter":
    range: [1.5, 1.5]
  "3000 meter":
    range: [3, 3]
  "5000 meter":
    range: [5, 5]
  "10000 meter":
    range: [10, 10]
  "5 km":
    range: [4, 6]
  "10 km":
    range: [9, 11]
  "Mila løp":
    range: [9, 11]
  "Halvmaraton":
    range: [20, 22]
  "Maraton":
    range: [40, 44]
  "Backyard Ultra": "backyard"
  "Ultraløp":
    range: [42, 500]
  "50 miles":
    range: [75, 100]
  "100 miles":
    range: [150, 170]
  "200 miles":
    range: [300, 500]
  "50 km":
    range: [45, 55]
  "100 km":
    range: [90, 110]
