collection_type: "Mosjonsløp"
sub_domain: race-pages
icon_path: /img/logo.svg
page_type_text: "Løpsside for"

show_all_local: "Vis alle"
url_text_top: "Lenke til påmelding"
about_local: "Om løpet"
info_local: "Detaljert informasjon"
disclaimer_text: |
  All info på denne siden er basert på åpen kildekode. Vi gjør vårt beste for å holde den oppdatert, men
  kan ikke garantere at alt er korrekt. Ser du noen feil, vennligst kontakt oss på 
  <a href="/kontakt.html">kontakt</a> så retter vi det så snart som mulig.

# Main labels
main_labels: ["Distanse", "Underlag", "Sted", "Dato"]
main_keys: ["display_distances", "type", "place", "date"]
icons: ["analytics", "shapes", "navigate-circle", "calendar-clear"]

# Components
map: True
mapbox_center: "61.7665242,9.5515165"
calendar: False

# Additional labels
additional_labels: ["Løpskategorier", "Fylke", "Arrangør"]
additional_keys: ["race_categories", "county", "organizer"]

url_text_bot: "Lenke til arrangørens nettside"
