# submission success PAGE CONTENT
submission_success_name: "submission-success"
title: "Tack för ditt bidrag!"
description: "Tack för ditt bidrag! Vi kommer att granska ditt lopp och lägga upp det så snart som möjligt."

# submission success PAGE
# SUBMISSION SUCCESS PAGE
submission_header: "Tack för ditt bidrag! Alla tillägg behöver granskas, men vi går löpande igenom loppen vi får in och kommer publicera ert snarast."
back_to_map_box_header: "Gå gärna tillbaka till vår loppkarta och kolla in alla andra lopp sålänge:"
map_button_text: "KARTAN"
list_button_text: "LISTAN"
